// angular-prototype/src/app/components/priority-badge/priority-badge.ts
import { Component, Input } from '@angular/core';
import type { TaskPriority } from '../../models';
import { PRIORITY_LABELS } from '../../models';

const PRIORITY_GLYPH: Record<TaskPriority, string> = {
  low: '↓',
  medium: '→',
  high: '↑',
};

@Component({
  selector: 'app-priority-badge',
  standalone: true,
  templateUrl: './priority-badge.html',
  styleUrl: './priority-badge.css',
})
export class PriorityBadgeComponent {
  @Input({ required: true }) priority!: TaskPriority;
  protected readonly PRIORITY_LABELS = PRIORITY_LABELS;
  protected readonly PRIORITY_GLYPH = PRIORITY_GLYPH;
}

// react-prototype/src/components/PriorityBadge/PriorityBadge.tsx
import type { TaskPriority } from '../../models';
import { PRIORITY_LABELS } from '../../models';
import styles from './PriorityBadge.module.css';

const PRIORITY_CLASS: Record<TaskPriority, string> = {
  low: styles.low,
  medium: styles.medium,
  high: styles.high,
};

const PRIORITY_GLYPH: Record<TaskPriority, string> = {
  low: '↓',
  medium: '→',
  high: '↑',
};

export function PriorityBadge({ priority }: { priority: TaskPriority }) {
  return (
    <span className={`badge ${PRIORITY_CLASS[priority]}`}>
      <span aria-hidden="true">{PRIORITY_GLYPH[priority]}</span>
      {PRIORITY_LABELS[priority]}
    </span>
  );
}
