// react-prototype/src/components/FormInput/FormInput.tsx
import styles from './FormInput.module.css';

interface FormInputProps {
  id: string;
  label: string;
  value: string;
  onChange: (value: string) => void;
  onBlur?: () => void;
  type?: 'text' | 'date';
  required?: boolean;
  error?: string | null;
  placeholder?: string;
}

export function FormInput({
  id,
  label,
  value,
  onChange,
  onBlur,
  type = 'text',
  required,
  error,
  placeholder,
}: FormInputProps) {
  return (
    <div className={styles.field}>
      <label htmlFor={id} className={styles.label}>
        {label}
        {required && (
          <span className={styles.required} aria-hidden="true">
            {' '}
            *
          </span>
        )}
      </label>
      <input
        id={id}
        type={type}
        className={`${styles.control} ${error ? styles.controlError : ''}`}
        value={value}
        placeholder={placeholder}
        onChange={(event) => onChange(event.target.value)}
        onBlur={onBlur}
        aria-invalid={!!error}
        aria-describedby={error ? `${id}-error` : undefined}
      />
      {error && (
        <p id={`${id}-error`} className={styles.error}>
          {error}
        </p>
      )}
    </div>
  );
}

// angular-prototype/src/app/components/form-input/form-input.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-form-input',
  standalone: true,
  templateUrl: './form-input.html',
  styleUrl: './form-input.css',
})
export class FormInputComponent {
  @Input({ required: true }) inputId!: string;
  @Input({ required: true }) label!: string;
  @Input() value = '';
  @Input() type: 'text' | 'date' = 'text';
  @Input() required = false;
  @Input() error: string | null = null;
  @Input() placeholder = '';
  @Output() valueChange = new EventEmitter<string>();
  @Output() blurred = new EventEmitter<void>();

  handleInput(event: Event): void {
    this.valueChange.emit((event.target as HTMLInputElement).value);
  }
}
